/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package addressbook;

import java.sql.*;
import javax.swing.JOptionPane;
public class loginPage extends javax.swing.JFrame {
        Connection conn = null;
        String url = "Jdbc:mysql://localhost:3306/";
        String dbName = "AddressBook";
        String driver = "com.mysql.jdbc.Driver";
        String username = "root";
        String password = "";
        
        ResultSet rs = null;
        PreparedStatement pst = null;
        
        
        
        
        
    public loginPage() {
        initComponents();
        try{
            
        //Create Driver object
            Class.forName(driver).newInstance();
            //connection
            conn = DriverManager.getConnection(url+dbName,username,password);
            
            //statement
            Statement statement = conn.createStatement();
            //Create Driver object
            Class.forName(driver).newInstance();

            //connection
            conn = DriverManager.getConnection(url+dbName,username,password);

            
        }catch(Exception e){
            
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username_tf = new javax.swing.JTextField();
        password_tf = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        login_b = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 20));

        username_tf.setToolTipText("Enter Your Correct Usernmae");
        username_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_tfActionPerformed(evt);
            }
        });
        getContentPane().add(username_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 121, -1));

        password_tf.setToolTipText("Enter Password for your User Name");
        password_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_tfActionPerformed(evt);
            }
        });
        getContentPane().add(password_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 123, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Get Permission");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 190, -1));

        login_b.setBackground(new java.awt.Color(102, 255, 51));
        login_b.setText("login");
        login_b.setToolTipText("Click to Access ");
        login_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_bActionPerformed(evt);
            }
        });
        getContentPane().add(login_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Guest");
        jButton1.setToolTipText("If you Don't Have Username , you can vist ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addressbook/pic/wall.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        setBounds(320, 130, 716, 388);
    }// </editor-fold>//GEN-END:initComponents

    private void login_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_bActionPerformed
        String sql = "select * from user where username =? and password = ?";
        
        try{

        pst = conn.prepareStatement(sql);
        pst.setString(1,username_tf.getText());
        pst.setString(2,password_tf.getText());

        rs = pst.executeQuery();
        if(rs.next()){
            MainPage mp= new MainPage();
            mp.setVisible(true);
            setVisible(false);
        }
        else{

        JOptionPane.showMessageDialog(null,"UsrName and Password is not Correct");

        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
     
    }//GEN-LAST:event_login_bActionPerformed

       
    
    private void password_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_tfActionPerformed
        login_bActionPerformed(evt);
    }//GEN-LAST:event_password_tfActionPerformed

    private void username_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_tfActionPerformed
        login_bActionPerformed(evt);
    }//GEN-LAST:event_username_tfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Guest g = new Guest();
        g.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login_b;
    private javax.swing.JPasswordField password_tf;
    private javax.swing.JTextField username_tf;
    // End of variables declaration//GEN-END:variables
}
